### ISSUE TITLE
Adapt bootstrap compilation to OSRM buildsystem changes

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/node-osrm#111]
I'm currently working on cleaning up some nasty buildsystem issues: https://github.com/Project-OSRM/osrm-backend/pull/1647 (read the commit messages, the pull request only tracks progress).

From what I can tell we have to adapt the [bootstrap.sh](https://github.com/Project-OSRM/node-osrm/blob/6651566a17f3462f749ef92c5dce03f334c5d63a/bootstrap.sh#L111-L127) script to these changes. Especially the hardcoded removal of coverage flags and lto is a problem, since the flags will change and the lto flag will be either `-flto` or `flto=N` where N is `$(ncpus)` (why is lto not used?).

Then, the [binding.gyp](https://github.com/Project-OSRM/node-osrm/blob/6651566a17f3462f749ef92c5dce03f334c5d63a/binding.gyp) seems to rely on OSRM's `pkg-config` config file which currently does _not_ contain all dependencies (why are those boost libs requires in addition [here?](https://github.com/Project-OSRM/node-osrm/blob/6651566a17f3462f749ef92c5dce03f334c5d63a/binding.gyp#L28-L29))

**Comment by springmeyer** [comment]
Great stuff.

> From what I can tell we have to adapt the bootstrap.sh script to these changes.

Hopefully only very minor adjustments.

> Especially the hardcoded removal of coverage flags and lto is a problem, since the flags will change and the lto flag will be either -flto or flto=N where N is $(ncpus) (why is lto not used?).

The lto was disabled due to https://github.com/Project-OSRM/node-osrm/issues/92.

Please feel free to removed these lines - hopefully your upstream changes will fix the problems I saw: https://github.com/Project-OSRM/node-osrm/blob/6651566a17f3462f749ef92c5dce03f334c5d63a/bootstrap.sh#L112-L113

> Then, the binding.gyp seems to rely on OSRM's pkg-config config file which currently does not contain all dependencies (why are those boost libs requires in addition here?)

Those boost libs could be provided by `pkg-config --libs`. But the convention I've seen is that `pkg-config --libs` only usually reports the main library, so `libosrm` in this case. And to get the rest of the dependent libraries I've seen the convention of `pkg-config --static`. But the problem with that is it would give more libraries than are actually used by node-osrm. For example `tbb` is not used by `node-osrm` that I know of. So we hardcoded, by trial and error, just those few boost libraries that seemed needed for linking to work. Feel free to revise this if you see a better way. I'm personally not very familiar with pkg-config ([nor a big fan](https://github.com/mapbox/mason/issues/12)) and prefer custom config scripts that accept custom options.

**Comment by daniel-j-h** [comment]
Check the test branch here: https://github.com/Project-OSRM/node-osrm/pull/112. On GCC < 4.9 there was an issue with LTO, so I added an exception for such versions. Now the GCC builds fails in the bindings with the following error:

```
make: Entering directory `/home/travis/build/Project-OSRM/node-osrm/build'
  CXX(target) Release/obj.target/osrm/src/node_osrm.o
  SOLINK_MODULE(target) Release/obj.target/osrm.node
/usr/bin/ld: /home/travis/build/Project-OSRM/node-osrm/mason_packages/.link/lib/libOSRM.a(compute_angle.cpp.o): relocation R_X86_64_32S against `.rodata._ZL10atan_table' can not be used when making a shared object; recompile with -fPIC
/home/travis/build/Project-OSRM/node-osrm/mason_packages/.link/lib/libOSRM.a: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
```

[Here](https://travis-ci.org/Project-OSRM/node-osrm/builds/80675963) is the travis page for it. [Here](https://github.com/Project-OSRM/osrm-backend/blob/cc36a28d2a48eb225bce259c6b2bfc6fb2ae278b/CMakeLists.txt#L378) we're setting the `-fPIC`/`-fPIE` flags for position independent code.

I'm not sure why Clang builds without problems, though.

**Comment by daniel-j-h** [comment]
@springmeyer all problems resolved as of now:

Here's the node-osrm branch that is pointing to the latest osrm-backend buildsystem branch's gitsha:
https://github.com/Project-OSRM/node-osrm/pull/112 --- travis is finally giving me thumbs up.

And here's the osrm-backend buildsystem branch which contains all of the actual changes:
https://github.com/Project-OSRM/osrm-backend/pull/1647

How to move forward here? Can I or @TheMarex just merge the buildsystem branch into osrm-backend develop, and we open a pull request for node-osrm that tracks the changes needed for node-osrm, to incorporate in the next release?

**Comment by daniel-j-h** [comment]
Talked to @TheMarex, the plan is this: we merge the buildsystem changes into osrm-backend develop, and delay the corresponding changes to node-osrm to the next release.

**Comment by springmeyer** [comment]
:+1: great work @daniel-j-h - feel free to merge https://github.com/Project-OSRM/node-osrm/pull/112 once you have a stable gitsha upstream to point to.

**Comment by daniel-j-h** [comment]
@springmeyer: I do have a stable osrm-backend gitsha, as I merged the osrm-backend part into develop already. The problem is, that I don't want to point node-osrm to a osrm-backend develop gitsha, but would rather see these changes go smoothly in with the next release. This would guarantee proper testing and QA.

**Comment by springmeyer** [comment]
Closing, we currently have node-osrm `develop` pointed at osrm-backend `develop`. Next actions are over at #126.
