### ISSUE TITLE
is the makefile broken?

### ISSUE THREAD

**Issue by tharrington** [Project-OSRM/node-osrm#138]
on mac, i download osrm and cd into node_modules/osrm/test/data and run the command

$ make berlin-latest.osrm.hsgr

it download 'berlin-latest.osm.pbf' but errors:
make: *** No rule to make target `/osrm-extract', needed by `berlin-latest.osrm'.  Stop.

My gcc out of date?

**Comment by daniel-j-h** [comment]
The `berlin-latest.osrm` target [depends on](https://github.com/Project-OSRM/node-osrm/blob/50ea6781190c0c4b547aebace770d87df4a8140d/test/data/Makefile#L22) `berlin-latest.osm.pbf`, `car.lua` and `$(OSRM_EXTRACT)`. `$(OSRM_EXTRACT)` [expands to](https://github.com/Project-OSRM/node-osrm/blob/50ea6781190c0c4b547aebace770d87df4a8140d/test/data/Makefile#L4) `$(TOOL_ROOT)/osrm-extract` --- and because you invoke the Makefile from the subdirectory, `$(TOOL_ROOT)` is not set (it gets [set here in the top level Makefile](https://github.com/Project-OSRM/node-osrm/blob/50ea6781190c0c4b547aebace770d87df4a8140d/Makefile#L2)).

Untested, but I think you can just set `$(TOOL_ROOT)` to the directory where `osrm-extract` is in, like this

    env TOOL_ROOT=../../lib/binding make

**Comment by TheMarex** [comment]
@tharrington if you want to run the tests, just run `make test` from the `node-osrm` project root.

**Comment by TheMarex** [comment]
Closing here, not actionable.
