### ISSUE TITLE
Validation errors should call the callback

### ISSUE THREAD

**Issue by willwhite** [Project-OSRM/node-osrm#164]
Input validation errors appear to be thrown rather than passed to the callback, which makes for some awkward code downstream. Right now, we need to do error checking in a try/catch *and* in the callback:

```javascript
try {
    osrm.tile([x, y, z], function(err, result) {
        if (err) return next(err);
    });
} catch(err) {
    return next(err);
}
```

It would be nice to consolidate this into:

```javascript
osrm.tile([x, y, z], function(err, result) {
    if (err) return next(err);
});
```

/cc @karenzshea

**Comment by TheMarex** [comment]
Yes. This problem exists for all plugins. What needs to happen is that: We add a `Nan::TryCatch` block for the parameter parsing and instead of just `return`ing like [here](
https://github.com/Project-OSRM/node-osrm/pull/152/files#diff-60ee113ce45e6a7a7b30e186170c46a1R876)
we would need to call the callback with the error, like we do [here](https://github.com/Project-OSRM/node-osrm/pull/152/files#diff-60ee113ce45e6a7a7b30e186170c46a1R1099).

**Comment by TheMarex** [comment]
Parameter validation throwing exceptions rather than calling the callback seems to be the norm across all native modules that I checked. To stay consistent here, we are going to leave this as is.
