### ISSUE TITLE
production example with multiple routing profiles?

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/node-osrm#205]
I found https://github.com/Project-OSRM/node-osrm/blob/master/example/server.js. Is this a realistic example of how to use node-osrm to serve routes in a production setup, or is there another example somewhere?

Our use case involves 3 different cycling profiles on different urls, running on Ubuntu 16.

**Comment by daniel-j-h** [comment]
One option to handle this is to run three independent express/koa apps: one for each profile (loading a different `.osrm`), listening on different ports. Dispatch onto them based on the URL (e.g. `/bike/elevation/*` goes to port `5001`, and so on).

Another option is to run a singe express/koa app, load your three `.osrm` files into three `OSRM` objects and dispatch in the URL handlers appropriately.

Both options are fine and depend on your exact use-case.
I prefer the first one since you don't get a single monolithic monster.

**Comment by daniel-j-h** [comment]
Closing here since it's not actionable for us.

Note: feel free to visit us in #osrm on oftc for these and related questions :)

**Comment by emiltin** [comment]
thanks. ok i will try #osrm :-)
