### ISSUE TITLE
data  processing workflow?

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/node-osrm#206]
is there documentation about the data processing workflow somewhere?

i've installed node-osrm on ubuntu 16 using 'npm install osrm'.

but how do i extract/contract data? is this still done using the osrm-extract and osrm-contract binaries, and is so, are they installed with node-osrm or do i need to build/install them separately?

thanks!

**Comment by daniel-j-h** [comment]
Use the `osrm-*` binaries that come with `node-osrm` (or build them separately but then be sure you have the same version for `node-osrm` and `osrm-backend`!)

    $ npm install osrm
    $ find . -type f -executable -name 'osrm*'
    ./node_modules/osrm/lib/binding/osrm.node
    ./node_modules/osrm/lib/binding/osrm-routed
    ./node_modules/osrm/lib/binding/osrm-extract
    ./node_modules/osrm/lib/binding/osrm-datastore
    ./node_modules/osrm/lib/binding/osrm-contract

Here's an example for how to run the pipeline:
https://github.com/Project-OSRM/node-osrm/blob/d02cb45d335248aadef3b742b19f8416328054d6/test/data/Makefile

The `osrm-backend` Wiki has more details, since `node-osrm` is a wrapper around `libosrm`:
https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM

**Comment by emiltin** [comment]
thank you
