### ISSUE TITLE
make fails: unable to find a working luabind (uses system's lua instead of mason's lua)

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/node-osrm#212]
Current master at [7b4f29b57](https://github.com/Project-OSRM/node-osrm/tree/7b4f29b57cd20bd14a03313195cf5a71afea2163):

```
git clone git@github.com:Project-OSRM/node-osrm.git
cd node-osrm
make
```

fails with:

```
-- Found Lua51: /usr/lib/x86_64-linux-gnu/liblua5.2.so;/usr/lib/x86_64-linux-gnu/libm.so  
-- Looking for LuaJIT 5.1
-- Could NOT find LUAJIT (missing:  LUAJIT_LIBRARIES) 
-- Performing Test LUABIND51_WORKS
-- Performing Test LUABIND51_WORKS - Failed
CMake Error at cmake/check_luabind.cmake:38 (message):
  Luabind does not work with Lua 5.1 at
  /usr/lib/x86_64-linux-gnu/liblua5.1.so, no working Luabind found
Call Stack (most recent call first):
  CMakeLists.txt:284 (include)
```

That is, it does not pick up the lua / luabind we're downloading from mason.

@MoKob just provided me with his OS X output:

```
-- Found Luabind: /Users/mokob/test/node-osrm/mason_packages/.link/lib/libluabind.a  
-- Found Luabind: /Users/mokob/test/node-osrm/mason_packages/.link/lib/libluabind.a
-- Found Lua52: /Users/mokob/test/node-osrm/mason_packages/.link/lib/liblua.a  
-- Performing Test LUABIND_WORKS
-- Performing Test LUABIND_WORKS - Success
-- Luabind/Lua5.2 combination working with /Users/mokob/test/node-osrm/mason_packages/.link/lib/liblua.a
```

which looks fine.

@springmeyer can you look into this?

**Comment by springmeyer** [comment]
If I am understanding right the problem is that you have duplicate libraries on your system and the system one is being found instead of the mason one. I presume this can be avoided (for your system) in at least two ways:

  - Uninstalling the system lib
  - Passing more flags to osrm-backend's cmake options to try to get cmake and the compiler to use the local libraries. Perhaps https://github.com/Project-OSRM/node-osrm/issues/172?

You could also try debugging if/why https://github.com/Project-OSRM/node-osrm/blob/master/bootstrap.sh#L173-L175 are not working, which should be ensuring that mason libs are used first. What may be happening is that the linux linker still prefers shared libraries over static. We prevent this on OS by using `-Wl,-search_paths_first`. Maybe linux has some equivalent?

**Comment by daniel-j-h** [comment]
Here's what I got so far:
- in `bootstrap.sh` `node-osrm` [install Lua 53](https://github.com/Project-OSRM/node-osrm/blob/7b4f29b57cd20bd14a03313195cf5a71afea2163/bootstrap.sh#L46)
- `osrm-backend`'s buildsystem only supports [Luabind with Lua52 or Lua51](https://github.com/Project-OSRM/osrm-backend/blob/f4db79fe9b644081d6b2478ba0f3e37b3e5cfcb9/cmake/check_luabind.cmake#L9) and tries to [find Lua52](https://github.com/Project-OSRM/osrm-backend/blob/master/cmake/FindLua52.cmake)

The fact that it works on some platforms seems to be that Lua53 is erroneously detected as Lua52.

I think the way forward here is to always install Luabind+Lua52 from mason or to completely re-write the Luabind+Lua detection part of `osrm-backend`'s buildsystem.

By the way @TheMarex is the Lua version we're shipping with `node-osrm` considered part of the API as in: user profiles may break when we ship Lua53 vs Lua52.

**Comment by springmeyer** [comment]
Going to close and hold on this, since extra work on lua is likely not worth it given upcoming work on nodejs alternative.

**Comment by daniel-j-h** [comment]
Reopening after discussion with @kkaefer and @danpat today.
We have to support Lua for the time being anyway.
And we're thinking of properly mason-izing osrm-backend.

**Comment by daniel-j-h** [comment]
Luabind is gone now. Closing this as stale.
