### ISSUE TITLE
Multi-host setup

### ISSUE THREAD

**Issue by snario** [Project-OSRM/node-osrm#215]
Is there any kind of example of a multi-host setup with OSRM? I'm just wondering if there is a way to scale this horizontally via # of hosts rather than vertically (getting a better host on AWS). Also are there benchmarks anywhere on how this performs?

I am hoping to run a large scale analysis to create millions of isochrones across North America and would like to understand what is the best way to run that job in the minimum amount of time.

Thanks! Appreciate any guidance.

**Comment by danpat** [comment]
@snario OSRM has a fairly monolithic design, there's nothing built-in for distributing work.

The simplest approach would be to:

  1. Pre-process your data for North America
  2. Start multiple EC2 instances with the processed datafiles
  3. Put a load balancer in front of them (like AWS ELB)
  4. Start hammering away

There are many other ways you could do it, including using the `node-osrm` bindings to avoid the HTTP overhead, but AFAIK, there's nothing pre-existing, you're going to need to figure out how to slice up the work and distribute it across machines.

I don't know if anyone has done the cost/performance analysis for distributing work this way.  You could slice up the datafiles and run smaller instances, but you'd then need to ensure the correct isochrone work went to a worker with sufficient map coverage to generate the isochrone you want.

Can you describe the project a bit more?  Do you need millions because you're pre-caching them?  Could on-the-fly generation work as well?

**Comment by daniel-j-h** [comment]
For this kind of workload it makes sense to use `libosrm` directly from C++. There is no need to go through Node bindings or even HTTP when all you want is distances / durations.

See the `example/example.cc` and you're halfway there :)

Distributing the workload is on you.
Maybe shard the work based on e.g. geographical tiles / values in a space filling curve.

**Comment by snario** [comment]
@daniel-j-h The only (working as far as I can tell) isochrone code I have found uses the node bindings so it is quite convenient for me to use one of them. Are there performance metrics for with node bindings / without node bindings for similar operations? Would give me a sense of whether or not I should pursue writing / extending a C++ isochrone implementation.

@danpat Thanks for the reply -- the analysis I am doing involves making these polygons at many locations across NA then joining the resulting polygons with other geographical demographic data (e.g., population) and then running queries across all the results.

**Comment by daniel-j-h** [comment]
Closing this as not actionable for us. Workload distribution is on you.

Here's a hint for large distance tables, though. Similar to how

https://github.com/stepankuzmin/distance-matrix

transparently decomposes a large distance table request into smaller ones and reassembles the responses again, you can do the same across multiple machines.
