### ISSUE TITLE
File path error on new OSRM object instance

### ISSUE THREAD

**Issue by jamelseagraves** [Project-OSRM/node-osrm#237]
So I built the osrm-backend and generated a .osrm file. Following the tutorial, I tried using that file as an input to create a new instance in the following script:
```
// Declare constants and variables
const fs = require('fs');
const csv = require('fast-csv');
const OSRM = require('osrm');
var osrm = new OSRM('../geodata/san-francisco.osrm');
var filepath = '../geodata/SF_Traffic_Accidents.csv';

if (fs.statSync(filepath).isFile()) {
	var readFileStream = fs.createReadStream(filepath, {encoding: 'utf8'});
	var csvReadStream = csv({headers: true, ignoreEmpty: true})
	.on('data', function(row) {
		osrm.nearest({coordinates: [[row.X,row.Y]]}, function(err, response) {
			if (err) return console.error(err);
			console.log(response.waypoints[0].location);
		});
	})
	.on('error', function(err) {
		console.error(err);
	})
	.on('end', function() {
		console.log('Finished streaming file');
	});
	readFileStream.pipe(csvReadStream);
};
```

Unfortuntately when I run the script, I get the following error:

TypeError: Invalid file paths given!
    at TypeError (native)
    at Object.<anonymous> (/Users/jseagra5/vecto-score/tasks/justify-accident-locations.js:8:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

Any suggestions to resolve this? Thanks in advance.

**Comment by danpat** [comment]
@jamelseagraves The node bindings come with a copy of `osrm-extract` and `osrm-contract`, you don't need to build it separately.  I'd guess that you've build a version of `osrm-backend` that doesn't match the node bindings you've used, and it's output incompatible files.

You can find `osrm-extract` and `osrm-contract` in `node_modules/osrm/lib/bindings`.  You may need to grab a copy of the Lua profile you used, make sure to copy it from the `osrm-backend` version that exactly matches the `node-osrm` version you've installed.

The `Invalid file paths given` error is what happens when some of the expected files are not found.  Different versions of OSRM generate different (and incompatible) files.

**Comment by jamelseagraves** [comment]
@danpat That makes total sense. I will give that a try.

Your help is much appreciated!

**Comment by jamelseagraves** [comment]
@danpat It works! Thanks again.
